library(readr)
groceries <- read.csv(file.choose())
View(groceries)
library(arules)
library(arulesViz)
class(groceries)

groceries1 <- as(groceries,"transactions")
inspect(groceries1)
summary(groceries1)
itemFrequencyPlot(groceries1,topN=20)
arules  <-  apriori(groceries1 ,parameter = list( support=0.0061, confidence= 0.50 , minlen= 3))
arules #88 rules
inspect(head(sort (arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")
arules  <-  apriori(groceries1 ,parameter = list( support=0.5, confidence= 0.5 , minlen= 3))
arules #0 rules
inspect(head(sort (arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")
arules  <-  apriori(groceries1 ,parameter = list( support=0.0071, confidence= 0.87 , minlen= 3))
arules #62 rules
inspect(head(sort (arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")
arules  <-  apriori(groceries1 ,parameter = list( support=0.0061, confidence= 1 , minlen= 3))
arules #60 rules
inspect(head(sort (arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")
arules  <-  apriori(groceries1 ,parameter = list( support=0.0061, confidence= 0.50 , minlen= 5))
arules #0 rules
inspect(head(sort (arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:20],method = "graph")