movies  <- my_movies[6:15]
my_movies <- read.csv("C:/Users/Giri/Desktop/ExcelR/assignments/Association Rules/my_movies.csv")
movies  <- my_movies[6:15]
movies$Sixth.Sense <- factor(movies$Sixth.Sense,levels = c("1","0"),labels=c("Sixth.Sense",""))
movies$Gladiator <- factor(movies$Gladiator,levels = c("1","0"),labels=c("Gladiator",""))
movies$LOTR1 <- factor(movies$LOTR1,levels = c("1","0"),labels=c("LOTR1",""))
movies$Harry.Potter1 <- factor(movies$Harry.Potter1, levels = c("1","0"),labels = c("Harry.Potter1",""))
movies$Patriot <- factor(movies$Patriot,levels = c("1","0"),labels = c("Patriot",""))
movies$LOTR2 <- factor(movies$LOTR2,levels = c("1","0"),labels = c("LOTR2",""))
movies$Harry.Potter2 <- factor(movies$Harry.Potter2,levels = c("1","0"),c("Harry.Potter2",""))
movies$LOTR <- factor(movies$LOTR,levels = c("1","0"),labels = c("LOTR",""))
movies$Green.Mile <- factor(movies$Green.Mile,levels = c("1","0"),labels = c("Green.Mile",""))
movies$Braveheart <- factor(movies$Braveheart,levels = c("1","0"),labels=c("Braveheart",""))
movies1 <- as(movies,"transactions")
inspect(movies1)
summary(movies1)
itemFrequencyPlot(movies1,topN=20)
arules <- apriori(movies1,parameter = list(support=0.5,confidence=0.6,minlen=3)) 
arules #2476 rules                 
inspect(head(sort(arules,by="lift"),n=20))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:50],method = "graph")
arules <- apriori(movies1,parameter = list(support=0.5,confidence=1,minlen=3)) 
arules #1785 rules                  
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:50],method = "graph")
arules <- apriori(movies1,parameter = list(support=0.9,confidence=0.6,minlen=3)) 
arules #0 rules                  
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:50],method = "graph")
arules <- apriori(movies1,parameter = list(support=0.5,confidence=0.6,minlen=2)) 
arules #2560 rules                  
inspect(head(sort(arules,by="lift")))
head(quality(arules))
plot(arules)
windows()
plot(arules,method = "grouped")
plot(arules[1:50],method = "graph")
