attach(ToyotaCorolla1)
plot(Age_08_04, Price)
plot(KM,HP)
pairs(ToyotaCorolla1)
cor(Age_08_04, Price)
cor(ToyotaCorolla1)
model.toyoto <- lm(Price ~ Age_08_04 + KM + HP + cc + Doors + Gears + Quarterly_Tax + Weight)
summary(model.toyoto)
model.toyoto_cc <- lm(Price ~ cc)
summary(model.toyoto_cc)
model.toyoto_Doors <- lm(Price ~ Doors)
summary(model.toyoto_Doors)
model.toyoto_cD <- lm(Price ~ cc + Doors)
summary(model.toyoto_cD)
library(GGally)
ggpairs(ToyotaCorolla1)
install.packages(car)
plot(model.toyoto)
qqplot(model.toyoto, id.n = 5)
influenceIndexPlot(model.toyoto, id.n = 3)
influencePlot(model.toyoto, id.n = 3)
model.toyoto1 <- lm(Price ~ Age_08_04 + KM + HP + cc + Doors + Gears + Quarterly_Tax + Weight, data = ToyotaCorolla1[-81, ])
summary(model.toyoto1)
vif(model.toyoto)
avPlots(model.toyoto, id.n=2, id.cex=0.8, col="red")
stepAIC(model.toyoto)
plot(model.toyoto)
model.final <-lm(Price ~ Age_08_04 + KM + HP + Gears + Quarterly_Tax + Weight)
summary(model.final)
model.final1 <- lm(Price ~ Age_08_04 + KM + HP + Gears + Quarterly_Tax + Weight, data = ToyotaCorolla1[-81,])
summary(model.final1)
avPlots(model.final1, id.n=2, id.cex=0.8, col="red")
vif(model.final1)
