attach(X50_Startups1)
dotchart(X50_Startups1$`R&D Spend`)
dotchart(Administration)
dotchart(`Marketing Spend`)
dotchart(Profit)
hist(X50_Startups1$`R&D Spend`)
hist(Administration)
hist(Profit)
hist(`Marketing Spend`)
boxplot(X50_Startups1$`R&D Spend`)
boxplot(Administration)
boxplot(Profit)
boxplot(`Marketing Spend`)
qqnorm(X50_Startups1$`R&D Spend`)
qqline(X50_Startups1$`R&D Spend`)
qqnorm(Profit)
qqline(Profit)
qqnorm(`Marketing Spend`)
qqline(`Marketing Spend`)
qqnorm(Administration)
qqline(Administration)
plot(X50_Startups1$`R&D Spend`,Profit)
plot(Administration,Profit)
plot(`Marketing Spend`,Profit)
pairs(X50_Startups1)
cor(X50_Startups1$`R&D Spend`,Profit)
cor(Administration,Profit)
cor(`Marketing Spend`,Profit)
cor(X50_Startups1)
model.X50<-lm(Profit~X50_Startups1$`R&D Spend`+Administration+`Marketing Spend`)
summary(model.X50)
model.X50_AD<-lm(Profit~Administration)
summary(model.X50_AD)
model.X50_MS<-lm(Profit~`Marketing Spend`)
summary(model.X50_MS)
model.X50_AM<-lm(Profit~Administration+`Marketing Spend`)
summary(model.X50_AM)
ggpairs(X50_Startups1)
plot(model.X50)
qqPlot(model.X50,id.n=5)
infIndexPlot(model.X50,id.n=3)
influencePlot(model.X50)
model.X50_1 <- lm(Profit~`R&D Spend`+Administration+`Marketing Spend`,data = X50_Startups1[-50, ])
summary(model.X50_1)
vif(model.X50)
avPlots(model.X50,id.n=2,id.cex=0.8,col="RED")
stepAIC(model.X50)
model.final<-lm(Profit~`R&D Spend`+`Marketing Spend`,data = X50_Startups1)
summary(model.final)
model.final1<-lm(Profit~`R&D Spend`+`Marketing Spend`,data = X50_Startups1[-50, ])
summary(model.final1)
